version: '3'

services:
  command-service:
    image: command-service
    container_name: command-service
    restart: always
    build:
      context: ./Ledger Command Service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: broker:29092
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb_1:3306/ledgerCommandDB?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - broker
      - mysqldb_1

  query-service:
    image: query-service
    container_name: query-service
    restart: always
    build:
      context: ./Ledger Query Service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: broker:29092
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb_2:3306/ledgerQueryDB?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - broker
      - mysqldb_2

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  mysqldb_1:
    container_name: mysqldb_1
    hostname: mysqldb_1
    image: "mysql:8.0.35"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ledgerCommandDB
      MYSQL_USER: sd58
      MYSQL_PASSWORD: sd58
      MYSQL_ROOT_PASSWORD: root
  mysqldb_2:
    container_name: mysqldb_2
    hostname: mysqldb_2
    image: "mysql:8.0.35"
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ledgerQueryDB
      MYSQL_USER: sd58
      MYSQL_PASSWORD: sd58
      MYSQL_ROOT_PASSWORD: root
